<head>
	<style type="text/css">
		#header{background-color: #590A1D; height: 75px; color:#fff; width:100%;}
		#srm_logo_img{height: 72px; width:72px;}
		#srm_logo{display: table;}
		#title_text{position: relative; display: table; margin: 0px auto; top:-70px;}


	</style>
</head>
<div id='header'>
		<div id='srm_logo'><img src="./srm_logo.png" id='srm_logo_img'></div>
		<div id='title_text'><h1>SRM UNIVERSITY</h1></div>
</div>